# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 14.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Test & publish code coverage
      uses: amancevice/setup-code-climate@v0
      with:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    - run: cc-test-reporter before-build
    - run: npm install
    - run: npm run cover
      env:
        CI: true
        PORT: ${{secrets.PORT}}
        MONGO_URI_TEST: ${{secrets.MONGO_URI_TEST}}
        JWT_SECRET: ${{secrets.JWT_SECRET}}
        JWT_EXPIRE: ${{secrets.JWT_EXPIRE}}
        JWT_COOKIE_EXPIRE: ${{secrets.JWT_COOKIE_EXPIRE}}
        CLOUDINARY_NAME: ${{secrets.CLOUDINARY_NAME}}
        CLOUDINARY_API_KEY: ${{secrets.CLOUDINARY_API_KEY}}
        CLOUDINARY_API_SECRET: ${{secrets.CLOUDINARY_API_SECRET}}
        NODE_ENV: ${{secrets.NODE_ENV}}
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    - run: cc-test-reporter after-build
